### ISSUE TITLE
PS4 support

### ISSUE THREAD

**Issue by xcier** [gibbed/Gibbed.Borderlands3#1]

**Comment by Ty-lerCox** [comment]
Save Wizard will likely be required for lastest firmware. I believe Save Wizard has to make the first move, and they're "taking a break for a few days".

**Comment by gibbed** [comment]
I will happily support differences in the PS4 save format, but I will not be supporting raw save data if the developers of the commercial save editors do that again (like they did with BL2/TPS).

If they do that again, you should ask them to add an option to give you the real save files.

**Comment by tobi-polar** [comment]
>  but I will not be supporting raw save data if the developers of the commercial save editors do that again (like they did with BL2/TPS).

what happened last time? and what needs to happen to have ps4 support?

**Comment by BuFu-EVO** [comment]
Shame save wizard have stated they will not have advanced mode on BL3 because it gives players online an unfair advantage, though its a PvE game and they have most of the advantages in the quick mode option already so that made ZER0 sense, and the stats are stored on the settings/profile save anyway so I'm lost as it gives no more of an advantage than bl2/TPS and bl goty.

**Comment by Ty-lerCox** [comment]
> Shame save wizard have stated they will not have advanced mode on BL3 because it gives players online an unfair advantage, though its a PvE game and they have most of the advantages in the quick mode option already so that made ZER0 sense, and the stats are stored on the settings/profile save anyway so I'm lost as it gives no more of an advantage than bl2/TPS and bl goty.

I agree. I wonder if we see websites selling modded weapons on PS4 in the future.

**Comment by xcier** [comment]
[borderlands 3.zip](https://github.com/gibbed/Gibbed.Borderlands3/files/3659162/borderlands.3.zip)
like i said if anyone can do anything with this i'll be more than happy to make the method public. It is a ps4 save
