### ISSUE TITLE
Software has turned to vaporware 

### ISSUE THREAD

**Issue by aepkolol** [gibbed/Gibbed.Borderlands3#6]
Issue: 26+ days since last release. No working version in sight. No communication. 

Suggest someone else takes over the project.

**Comment by singh87** [comment]
It wouldn't be that hard if someone can decrypt the pc save file.

**Comment by mandingocc6901** [comment]
I was thinking about contributing, but I can't justify doing so if there aren't even updates on progress indicating that any activity is taking place.

**Comment by josiec09** [comment]
I think people are forgetting he has a life outside of making the save editor....on top of that he is working on it for free.  

As for communication: 
> Rick@gibbed·Oct 7
> Yeah I'm going with the "only posting updates when there's an actual update". Not going to say "no change, sorry" daily.

> Rick@gibbed·Oct 1
> #Borderlands3 save editor update: Yeah, didn't make it in time for Shadowkeep. Going to play a bit of Shadowkeep and work more on the save editor later tonight. 

> Rick@gibbed·Sep 27
> #Borderlands3 save editor update: Not tonight, unexpected stuff came up (unrelated to save editor) and didn't get the part editor into a state I'm happy with, with the time I had available today.
> 
> New goal for release is before Tuesday (Shadowkeep's release).

> Rick@gibbed·Sep 27
> I'm glad many people are excited for the #Borderlands3 save editor, but please don't pollute my tweets unrelated to the save editor with off-topic replies asking for an update.
> 
> If and when I have an update, I will tweet about it. 👌

> Rick@gibbed·Sep 23
> For the release of my #Borderlands3 save editor:
> 
> My goal is to release the editor on or before this upcoming Friday.
> 
> That's not a guarantee. Could be sooner, could be later.

We will most likely get an update some point this weekend or next week. The save editor will be released when its ready. No ETA yet. Borderlands 3 is not going anywhere.

**Comment by dbotamous** [comment]
Lol chill. This is a random dude, with a life, working on this in his spare time. On top of all that, he's giving this to you (and all of us) for free. He owes you nothing.

**Comment by aepkolol** [comment]
The communication was "Should be out October 1st" last I heard. Now we're almost 2 weeks later. No, he doesn't owe us anything. Obviously. I know there are some people out there that would have worked on this, but know gibbed could do it better, and has been working on it. I'm just saying, its basically vaporware now. If you wana play shadow keep, why not update the repo and let someone else finish it. That's one of the great parts of open source, isn't it?

**Comment by gibbed** [comment]
I hold my own code to a certain set of quality standards and generally don't release it until I feel it satisfies those standards.

The fact that I open source the code that I develop doesn't mean I've chosen to cede control over how I wish to make it available. Perhaps if I think I've chosen to abandon the project, _then_ I would consider releasing incomplete code.
